spring:
  application:
    name: graphql-dgs-netflix
  jpa:
    # Provide database platform that is being used
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # Format queries
      format_sql: true
      ddl-auto: create
    # Show sql when spring data jpa performs query
    show-sql: true
  datasource:
    # URL connection to database (ecommerce is database name)
    url: jdbc:h2:mem:ecommerce
    # H2 sql Driver
    driver-class-name: org.h2.Driver
    username: root
    password: 12345
  h2:
    console:
      enabled: true
  sql:
    init:
      platform: h2
      # Executes schema creation and data insertion scripts on every application start
      mode: always
